version: '2.1'
orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@0.0.10
jobs:
  install dependecies:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          node-version: '18.3'
      - run: node --version
workflows:
  test_and_deploy:
    jobs:
      - node/test
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          filters:
            branches:
              only: main
